
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CalculatriceWSService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8089/?wsdl")
public class CalculatriceWSService
    extends Service
{

    private final static URL CALCULATRICEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATRICEWSSERVICE_EXCEPTION;
    private final static QName CALCULATRICEWSSERVICE_QNAME = new QName("http://service/", "CalculatriceWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATRICEWSSERVICE_WSDL_LOCATION = url;
        CALCULATRICEWSSERVICE_EXCEPTION = e;
    }

    public CalculatriceWSService() {
        super(__getWsdlLocation(), CALCULATRICEWSSERVICE_QNAME);
    }

    public CalculatriceWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATRICEWSSERVICE_QNAME, features);
    }

    public CalculatriceWSService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATRICEWSSERVICE_QNAME);
    }

    public CalculatriceWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATRICEWSSERVICE_QNAME, features);
    }

    public CalculatriceWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatriceWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatriceWS
     */
    @WebEndpoint(name = "CalculatriceWSPort")
    public CalculatriceWS getCalculatriceWSPort() {
        return super.getPort(new QName("http://service/", "CalculatriceWSPort"), CalculatriceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatriceWS
     */
    @WebEndpoint(name = "CalculatriceWSPort")
    public CalculatriceWS getCalculatriceWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "CalculatriceWSPort"), CalculatriceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATRICEWSSERVICE_EXCEPTION!= null) {
            throw CALCULATRICEWSSERVICE_EXCEPTION;
        }
        return CALCULATRICEWSSERVICE_WSDL_LOCATION;
    }

}
